services:
  - type: web
    name: bossaix-galaxy
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    plan: free
    envVars: {}
    staticPublishPath: "public"
